### ISSUE TITLE
Update The README.md file 

### ISSUE THREAD

**Issue by iamdharmveer** [iamdharmveer/TributeAPJKalam#2]
Check out the link for more details  https://iamdharmveer.github.io/TributeAPJKalam/
the documentation would need to be created using the Rust documentation format.

**Comment by iamdharmveer** [comment]
https://doc.rust-lang.org/book/documentation.html

**Comment by realslimshanky** [comment]
I wanna help you with this.
Will send a PR with the update soon.

**Comment by iamdharmveer** [comment]
@realslimshanky okay 👍

**Comment by realslimshanky** [comment]
@iamdharmveer Please give specification of your documentation.

**Comment by iamdharmveer** [comment]
@realslimshanky https://iamdharmveer.github.io/TributeAPJKalam/

**Comment by realslimshanky** [comment]
@iamdharmveer you want to change you complete web page into a RUST document ?

**Comment by iamdharmveer** [comment]
NO

**Comment by realslimshanky** [comment]
then ?

**Comment by VickyRampin** [comment]
I think he wants the README.md to be a rustdoc instead of markdown? Is that right, @iamdharmveer ?

**Comment by iamdharmveer** [comment]
@VickySteeves yes 👍
